//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RvLinkDeviceTester.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RvLinkDeviceTester.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add And Manage.
        /// </summary>
        public static string add_and_manage {
            get {
                return ResourceManager.GetString("add_and_manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RvLink Tester.
        /// </summary>
        public static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string connect_title {
            get {
                return ResourceManager.GetString("connect_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics.
        /// </summary>
        public static string diagnostics_title {
            get {
                return ResourceManager.GetString("diagnostics_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string disconnect_title {
            get {
                return ResourceManager.GetString("disconnect_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send logs via e-mail.
        /// </summary>
        public static string email_logs_description {
            get {
                return ResourceManager.GetString("email_logs_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail Logs.
        /// </summary>
        public static string email_logs_title {
            get {
                return ResourceManager.GetString("email_logs_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Notifications on Alert Change.
        /// </summary>
        public static string generate_notifications_on_alert_change_setting {
            get {
                return ResourceManager.GetString("generate_notifications_on_alert_change_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Part Number.
        /// </summary>
        public static string get_part_number {
            get {
                return ResourceManager.GetString("get_part_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get History Data.
        /// </summary>
        public static string history_data {
            get {
                return ResourceManager.GetString("history_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key/Seed Exchange.
        /// </summary>
        public static string key_seed_title {
            get {
                return ResourceManager.GetString("key_seed_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string log_severity_debug {
            get {
                return ResourceManager.GetString("log_severity_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string log_severity_error {
            get {
                return ResourceManager.GetString("log_severity_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string log_severity_information {
            get {
                return ResourceManager.GetString("log_severity_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string log_severity_warning {
            get {
                return ResourceManager.GetString("log_severity_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Viewer.
        /// </summary>
        public static string log_viewer_title {
            get {
                return ResourceManager.GetString("log_viewer_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mac Address Pairing.
        /// </summary>
        public static string mac_address_pair_title {
            get {
                return ResourceManager.GetString("mac_address_pair_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap the &apos;+&apos; icon to connect to your devices..
        /// </summary>
        public static string main_page_empty_label {
            get {
                return ResourceManager.GetString("main_page_empty_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push to Pair.
        /// </summary>
        public static string push_to_pair_title {
            get {
                return ResourceManager.GetString("push_to_pair_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove accessory.
        /// </summary>
        public static string remove_accessory {
            get {
                return ResourceManager.GetString("remove_accessory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this accessory?.
        /// </summary>
        public static string remove_accessory_question {
            get {
                return ResourceManager.GetString("remove_accessory_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all.
        /// </summary>
        public static string remove_all {
            get {
                return ResourceManager.GetString("remove_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all accessories.
        /// </summary>
        public static string remove_all_accessories {
            get {
                return ResourceManager.GetString("remove_all_accessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove all accessories?.
        /// </summary>
        public static string remove_all_accessories_question {
            get {
                return ResourceManager.GetString("remove_all_accessories_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings_title {
            get {
                return ResourceManager.GetString("settings_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload logs to LCI.
        /// </summary>
        public static string upload_logs_description {
            get {
                return ResourceManager.GetString("upload_logs_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Logs.
        /// </summary>
        public static string upload_logs_title {
            get {
                return ResourceManager.GetString("upload_logs_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Key/Seed Exchange.
        /// </summary>
        public static string use_key_seed_title {
            get {
                return ResourceManager.GetString("use_key_seed_title", resourceCulture);
            }
        }
    }
}
